# Generated by Django 4.2.1 on 2023-05-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Gender',
        ),
        migrations.AddField(
            model_name='person',
            name='female',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='person',
            name='male',
            field=models.BooleanField(default=False, verbose_name='Male'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
