# Generated by Django 4.2.1 on 2023-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_person_gender_person_female_person_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='female',
        ),
        migrations.RemoveField(
            model_name='person',
            name='male',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=False, verbose_name=('Male', 'Female')),
        ),
    ]
