# Generated by Django 4.2.1 on 2023-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_remove_person_gender_person_female'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Female',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(choices=[('M', 'Male'), ('F', 'Female')], null=True),
        ),
    ]
