# Generated by Django 4.2.1 on 2023-05-23 06:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_gender_materials_required_remove_person_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='materials_required',
            name='materials_required',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dnb', 'Debit Note Book'), ('pen', 'Pen'), ('ep', 'Exam_Papers')], max_length=100),
        ),
    ]
