# Generated by Django 4.2.1 on 2023-05-23 07:08

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_alter_gender_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female')], max_length=40),
        ),
        migrations.AlterField(
            model_name='materials_required',
            name='materials_required',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dnb', 'Debit Note Book'), ('pen', 'Pen'), ('ep', 'Exam_Papers')], max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(blank=True, max_length=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='materials_required',
            field=models.ForeignKey(blank=True, max_length=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.materials_required'),
        ),
    ]
